// SCENE INDEX — DATA
// Structured by chapter. To add a new chapter, append an object to CHAPTERS.
// A chapter with an empty `scenes` array (and no sharedScene/closingScene)
// automatically renders as the "not yet published" empty state.
// Generated by editor.html on 2026-09-10T20:13:27.192Z

// The hero subtitle on the front page (editable from editor.html — "Main blurb").
const MAIN_BLURB = 'read with caution';

const CHAPTERS = [
  {
    number: 1,
    title: 'ruumissielu - henki - itse',
    sharedScene: {
      scene: 1,
      label: 'chapter 1 · opening scene · ainia',
      title: 'the etiäinen',
      allusions: ['cat 22', 'fatso', 'anti-shine gel'],
      url: 'https://unibodyinfinity.substack.com/p/the-etiainen',
      excerpt: 'When I get to the top I will open the door, run to the ledge, and wave at me inside our car.\n\nI will have someone else’s smile on my face, knowing.',
    },
    closingScene: {
      scene: 16,
      label: 'chapter 1 · closing scene · ainia',
      title: 'the wall',
      allusions: ['connected to all of ainia'],
      url: 'https://unibodyinfinity.substack.com/p/the-wall?r=2ofjql&utm_campaign=post&utm_medium=web&showWelcomeOnShare=true',
      excerpt: 'I’ll come find you.',
    },
    scenes: [
      {
        scene: 2,
        ui: { title: 'anti-shine gel', allusions: ['fatso'], url: 'https://unibodyinfinity.substack.com/p/anti-shine-gel?r=2ofjql', excerpt: 'No longer visible even to yourself, two quadrillion years in the future, at precisely ten minutes past five in the morning, the entirety of our universe is left behind.' },
        rh: { title: 'a handbag', allusions: ['ditmas junior high'], url: 'https://unibodyinfinity.substack.com/p/a-handbag?r=2ofjql', excerpt: 'Dad maybe she is dead, I saw her handbag! (the one I gave her) Stop!' },
      },
      {
        scene: 3,
        ui: { title: 'preonic anomally', allusions: ['cat 22'], url: 'https://unibodyinfinity.substack.com/p/preonic-anomally?r=2ofjql', excerpt: '...bounded by c —by all that it was ever able to see...' },
        rh: { title: 'stop the car dad', allusions: ['a fenderbender'], url: 'https://unibodyinfinity.substack.com/p/stop-the-car-dad?r=2ofjql', excerpt: 'traffic accident with ourselves' },
      },
      {
        scene: 4,
        ui: { title: 'pissing contest', allusions: ['crazy experiment'], url: 'https://unibodyinfinity.substack.com/p/pissing-contest?r=2ofjql', excerpt: 'traveling within a void going on for aeons, you evolve into other beings, even species, a denisovan, a neanderthal, and back to yourself again, checking on the void for any signs of progress.' },
        rh: { title: 'who are you', allusions: ['anti-shine gel'], url: 'https://unibodyinfinity.substack.com/p/who-are-you?r=2ofjql', excerpt: 'Giving my family a one last glance, I jump to the scaffolding.' },
      },
      {
        scene: 5,
        ui: { title: 'different color for black', allusions: ['aina', 'cat 22', 'the mansion'], url: 'https://unibodyinfinity.substack.com/p/different-color-for-black?r=2ofjql', excerpt: 'It has a different color for black, even when you shut your eyes.' },
        rh: { title: 'crazy experiment', allusions: ['plain vanilla dad', 'why me'], url: 'https://unibodyinfinity.substack.com/p/crazy-experiment?r=2ofjql', excerpt: 'I had partially disassembled an amplifier/receiver from our hi-fi system, partially destroyed a calculator, and conjoined them to make an organ...' },
      },
      {
        scene: 6,
        ui: { title: 'turquoise blue typewriter', allusions: ['pale blue typewriter'], url: 'https://unibodyinfinity.substack.com/p/turquoise-blue-typewriter?r=2ofjql', excerpt: 'You would write each new page on top of the existing old texts typed, making the written lines look like one whole page of redactions.' },
        rh: { title: 'pale blue typewriter', allusions: ['turquoise blue typewriter'], url: 'https://unibodyinfinity.substack.com/p/pale-blue-typewriter?r=2ofjql', excerpt: 'We boarded the train to Manhattan from Ronkonkoma with a big smile on dad’s face.' },
      },
      {
        scene: 7,
        ui: { title: 'a fenderbender', allusions: ['aina', 'fatso', 'scintillating words'], url: 'https://unibodyinfinity.substack.com/p/bending-your-own-fender?r=2ofjql', excerpt: ' But while still in the suburbs of it, you start seeing other yous.' },
        rh: { title: 'aina', allusions: ['a fenderbender'], url: 'https://unibodyinfinity.substack.com/p/aina?r=2ofjql', excerpt: 'aina’s note: this is not me\n' },
      },
      {
        scene: 8,
        ui: { title: 'the entanglement hook', allusions: ['fatso', 'scintillating words'], url: 'https://unibodyinfinity.substack.com/p/the-entanglement-hook?r=2ofjql', excerpt: 'Playing a dangerous game I engage the entanglement hook directly onto my thalamic relay.' },
        rh: { title: 'knowing', allusions: ['why me'], url: 'https://unibodyinfinity.substack.com/p/knowing?r=2ofjql', excerpt: '“You came here to save me but who is coming to save you?” She asks.' },
      },
      {
        scene: 9,
        ui: { title: 'kaleva', allusions: ['fatso', 'scintillating words'], url: 'https://unibodyinfinity.substack.com/p/kaleva?r=2ofjql', excerpt: 'Your pompous grandiosity is not enough to make us forget how you destroyed a whole universe with trillions of lives in it, instead of trying to understand it.' },
        rh: { title: 'happy birthday', allusions: ['why me'], url: 'https://unibodyinfinity.substack.com/p/gobble-gobble?r=2ofjql', excerpt: '“my birthday is in a couple of days, and I have several birthdays, one is three months from now, and the last one was at a time when there were no days”' },
      },
      {
        scene: 10,
        ui: { title: 'it\'s shrinking us', allusions: ['no connected scenes on the map of confusion ... yet.'], url: 'https://unibodyinfinity.substack.com/p/its-shrinking-us?r=2ofjql', excerpt: 'Don’t worry, what voids do is not noticeable. But do worry about that subatomic multiverse. It’s too big.' },
        rh: { title: 'ditmas junior high', allusions: ['why me'], url: 'https://unibodyinfinity.substack.com/p/ditmas-junior-high?r=2ofjql', excerpt: 'They told me that as the numbers after the slash got smaller, you got smarter.' },
      },
      {
        scene: 11,
        ui: { title: 'take a break', allusions: ['no connected scenes on the map of confusion ... yet.'], url: 'https://unibodyinfinity.substack.com/p/take-a-break?r=2ofjql', excerpt: '“How long have you been like that?” I ask.\nYou say some silly number; fifty six to the power of fifty six quinquavigintillion years, or some such.' },
        rh: { title: 'my friend timothy', allusions: ['allow me to introduce to you your daughter - chapter 2'], url: 'https://unibodyinfinity.substack.com/p/allow-me-to-introduce-to-you-my-friend?r=2ofjql', excerpt: '...I am not nitpicking, but no picnicking at...' },
      },
      {
        scene: 12,
        ui: { title: 'money money money', allusions: ['scintillating words'], url: 'https://unibodyinfinity.substack.com/p/money-money-money?r=2ofjql', excerpt: '...when spent correctly, it would regenerate more value than what was spent.' },
        rh: { title: 'cat 22', allusions: ['the entanglement hook'], url: 'https://unibodyinfinity.substack.com/p/cat-22?r=2ofjql', excerpt: 'Look at monsieur M…. zleeping, oooh, look at \'im punching ze pillow, oh mon dieu ! Now \'e is zitting up zleeping wiz \'is eyes open, oooh, anozer monsieur M…. is zitting on ze wall acting like a statue, oooouu, monsieur M…. \'as no eyes now, oooouuuu, monsieur M…. eez looking at me wiz \'is eyes at ze back of \'is head, oooouuuu, \'e eez angry, ouuuuu, Oh putain !' },
      },
      {
        scene: 13,
        ui: { title: 'give this to me', allusions: ['cat 22 -aina\'s note'], url: 'https://unibodyinfinity.substack.com/p/give-this-to-me?r=2ofjql', excerpt: 'It turned out to be an unreliable room, a trickster room...' },
        rh: { title: 'the mansion', allusions: ['different color for black', 'why me'], url: 'https://unibodyinfinity.substack.com/p/the-mansion?r=2ofjql', excerpt: 'he looked straight into me for a split second, the way one would look at a mirror' },
      },
      {
        scene: 14,
        ui: { title: 'why me', allusions: ['aina', 'knowing', 'cat 22'], url: 'https://unibodyinfinity.substack.com/p/why-me?r=2ofjql', excerpt: 'You think you think.' },
        rh: { title: 'fatso', allusions: ['anti-shine gel', 'different color for black'], url: 'https://unibodyinfinity.substack.com/p/fatso?r=2ofjql', excerpt: '...once she told me her blood was green!' },
      },
      {
        scene: 15,
        ui: { title: 'plain vanilla dad', allusions: ['aina'], url: 'https://unibodyinfinity.substack.com/p/plain-vanilla-dad?r=2ofjql&utm_campaign=post&utm_medium=web&showWelcomeOnShare=true', excerpt: 'how you are supposed to reverse-engineer time dilation, something that was never engineered in the first place' },
        rh: { title: 'scintillating words', allusions: ['the entanglement hook'], url: 'https://unibodyinfinity.substack.com/p/scintillating-words?r=2ofjql&utm_campaign=post&utm_medium=web&showWelcomeOnShare=true', excerpt: '...he claims he is not here but at the end of existence. Yeah, those are his exact words, end of everything, that’s what he says. He says he went to the moon driving an ox cart. He says he is at the layer eight of the skies. He says he has a something called sampu, shampoo, that keeps the sky up. He says if he’d let go all light would be gone, everything would turn into one solid piece of green dark.' },
      },
    ],
  },
  {
    number: 2,
    title: 'ilmarinen takoo sammon',
    sharedScene: null,
    closingScene: null,
    scenes: [],
  },
  {
    number: 3,
    title: '',
    sharedScene: null,
    closingScene: null,
    scenes: [],
  },
  {
    number: 4,
    title: '',
    sharedScene: null,
    closingScene: null,
    scenes: [],
  },
];
