// SCENE INDEX — DATA
// Generated by editor.html on 2026-08-17T21:34:51.514Z

const SHARED_SCENE = {
  scene: 1,
  title: 'the etiäinen',
  url: 'https://unibodyinfinity.substack.com/p/the-etiainen',
  excerpt: 'When I get to the top I will open the door, look towards our car just passing by, see myself in it, looking at me. I will wave at myself, someone else’s smile on my face, knowing.',
};

const SCENES = [
  {
    scene: 2,
    ui: { title: 'anti-shine gel', url: 'https://unibodyinfinity.substack.com/p/anti-shine-gel?r=2ofjql', excerpt: 'No longer visible even to yourself, two quadrillion years in the future, at precisely ten minutes past five in the morning, the entirety of this existence is left behind.' },
    rh: { title: 'a handbag', url: 'https://unibodyinfinity.substack.com/p/a-handbag?r=2ofjql', excerpt: 'It’s a red handbag. Its strap is broken.' },
  },
  {
    scene: 3,
    ui: { title: 'preonic anomally', url: 'https://unibodyinfinity.substack.com/p/preonic-anomally?r=2ofjql', excerpt: '...bounded by c —by all that it was ever able to see...' },
    rh: { title: 'stop the car dad', url: 'https://unibodyinfinity.substack.com/p/stop-the-car-dad?r=2ofjql', excerpt: ' I’ve never seen my father so frightened. ' },
  },
  {
    scene: 4,
    ui: { title: 'pissing contest', url: 'https://unibodyinfinity.substack.com/p/pissing-contest?r=2ofjql', excerpt: 'Traveling within a void going on for so many aeons, you evolve into other beings, or even things, out of boredom and back to what you are, just for spite.' },
    rh: { title: 'who are you', url: 'https://unibodyinfinity.substack.com/p/who-are-you?r=2ofjql', excerpt: 'Don’t follow me dad! Don’t wait for me! I know the way, I’ll make it back to our house!' },
  },
  {
    scene: 5,
    ui: { title: 'different color for black', url: 'https://unibodyinfinity.substack.com/p/different-color-for-black?r=2ofjql', excerpt: 'If it wasn’t for the Planck scale deviation of the anti-geodesic route and signal degradation...' },
    rh: { title: 'crazy experiment', url: 'https://unibodyinfinity.substack.com/p/crazy-experiment?r=2ofjql', excerpt: 'Look, dad, when you calculate 21621 + 21621, that Mozart piece comes out of the speakers.' },
  },
  {
    scene: 6,
    ui: { title: 'turquoise blue typewriter', url: 'https://unibodyinfinity.substack.com/p/turquoise-blue-typewriter?r=2ofjql', excerpt: '...or write prose like this one, using a turquoise blue, old fashioned typewriter on a single A4 sized page... ' },
    rh: { title: 'pale blue typewriter', url: 'https://unibodyinfinity.substack.com/p/pale-blue-typewriter?r=2ofjql', excerpt: 'We boarded the train to Manhattan from Ronkonkoma with a big smile on dad’s face.' },
  },
  {
    scene: 7,
    ui: { title: 'a fenderbender', url: 'https://unibodyinfinity.substack.com/p/bending-your-own-fender?r=2ofjql', excerpt: ' But while still in the suburbs of it, you start seeing other yous.' },
    rh: { title: 'aina', url: 'https://unibodyinfinity.substack.com/p/aina?r=2ofjql', excerpt: 'When I get to the final landing I see the handbag, right exactly at the spot where my vision first saw it.' },
  },
  {
    scene: 8,
    ui: { title: 'the entanglement hook', url: 'https://unibodyinfinity.substack.com/p/the-entanglement-hook?r=2ofjql', excerpt: 'Playing a dangerous game I engage the entanglement hook directly onto my thalamic relay.' },
    rh: { title: 'knowing', url: 'https://unibodyinfinity.substack.com/p/knowing?r=2ofjql', excerpt: '“You came here to save me but who is going to save you?” She asks.' },
  },
  {
    scene: 9,
    ui: { title: 'kaleva', url: 'https://unibodyinfinity.substack.com/p/kaleva?r=2ofjql', excerpt: '...the mirror on top of the dresser cracked just a little bit, a micro crack, on its top right corner...' },
    rh: { title: 'happy birthday', url: 'https://unibodyinfinity.substack.com/p/gobble-gobble?r=2ofjql', excerpt: '...it echoes from itself...' },
  },
  {
    scene: 10,
    ui: { title: 'it\'s shrinking us', url: 'https://unibodyinfinity.substack.com/p/its-shrinking-us?r=2ofjql', excerpt: 'Don’t worry, what voids do is not noticeable. But do worry about that subatomic multiverse. It’s too big.' },
    rh: { title: 'ditmas junior high', url: 'https://unibodyinfinity.substack.com/p/ditmas-junior-high?r=2ofjql', excerpt: 'They told me that as the numbers after the slash got smaller, you got smarter.' },
  },
  {
    scene: 11,
    ui: { title: 'take a break', url: 'https://unibodyinfinity.substack.com/p/take-a-break?r=2ofjql', excerpt: '“How long have you been like that?” I ask.\nYou say some silly number; fifty six to the power of fifty six quinquavigintillion years, or some such.' },
    rh: { title: 'allow me to introduce to you my friend; timothy', url: 'https://unibodyinfinity.substack.com/p/allow-me-to-introduce-to-you-my-friend?r=2ofjql', excerpt: '...I am not nitpicking, but no picnicking at...' },
  },
  {
    scene: 12,
    ui: { title: 'money money money', url: 'https://unibodyinfinity.substack.com/p/money-money-money?r=2ofjql', excerpt: 'I searched deeper into the far corners ... and extracted some diamonds ... one of the stones possibly enabling me to purchase half of the country... though I chose to leave them all behind.' },
    rh: { title: 'cat 22', url: 'https://unibodyinfinity.substack.com/p/cat-22?r=2ofjql', excerpt: 'Look at monsieur M…. zleeping, oooh, look at \'im punching ze pillow, oh mon dieu ! Now \'e is zitting up zleeping wiz \'is eyes open, oooh, anozer monsieur M…. is zitting on ze wall acting like a statue, oooouu, monsieur M…. \'as no eyes now, oooouuuu....' },
  },
  {
    scene: 13,
    ui: { title: 'give this to me', url: 'https://unibodyinfinity.substack.com/p/give-this-to-me?r=2ofjql', excerpt: 'It turned out to be an unreliable room, a trickster room...' },
    rh: { title: 'the mansion', url: 'https://unibodyinfinity.substack.com/p/the-mansion?r=2ofjql', excerpt: 'A homeless man ... passed ... by... he looked into me ...  the way one would look at a mirror.' },
  },
  {
    scene: 14,
    ui: { title: 'why me', url: 'https://unibodyinfinity.substack.com/p/why-me?r=2ofjql', excerpt: 'You think you think.' },
    rh: { title: 'fatso', url: 'https://unibodyinfinity.substack.com/p/fatso?r=2ofjql', excerpt: '...once she told me her blood was green!' },
  },
  {
    scene: 15,
    ui: null,
    rh: null,
  },
];
